### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jingwei-li** [jadecci/cbpp#2]
The following issues need to be fixed:

- `cbpp/bin/procedure_descriptions/README.md`

  Under `cross-validation procedure with hyperparameter tuning`, `Input data` box: dimension of FC for parcel-wise CBPP should be `(P-1)xN`.

- https://github.com/jadecci/cbpp/tree/master/bin/extraction_scripts#hcp-ya-data-extraction  : typo "correponsing"

- Are the csv filenames hard-coded in the scripts always fixed for any user around the world? For example, if one download eNKI NEO data by him/herself, would the filename also be called `8100_NEO-FFI-3_20180806.csv`?

- https://github.com/jadecci/cbpp/tree/master/bin/benchmarks#hcp-surface-cbpp-benchmark-information : typo "run-tim"

- Question again for the Benchmark readme: do you mean the resource usage of EN and RR should be multiplied by 100 to be compared with SVR and LRR because the #psychometric measures are different? Maybe it's clearer to write the number of repeats and psychometric measures in the title of each table.

- https://github.com/jadecci/cbpp/tree/master/bin/evaluation_scripts#evaluation : typo "interpretabbility".

- https://github.com/jadecci/cbpp/blob/master/bin/images/evaluation_readme_img1.png : typo "spychometric".

- https://github.com/jadecci/cbpp/blob/master/HCP_CBPP/README.md

  For the last chunk of code:
  ```
  options = struct('space', 'MNI', 'preproc', 'fix', 'fc_method', 'Pearson', 'reg_method', 'SVR');
  HCP_cbpp('region-wise', in_dir, out_dir, options);
  ```

  If you don't pass in the parcellation resolution, isn't the default 300, which is inconsistent with your description above?

- https://github.com/jadecci/cbpp/blob/dd27c86fedcd08d6e0849acdbf661e61e4d4783d/generalisability_CBPP/generalise_data_proc.m#L166

  Actually this subfunction is not to "compute parcellation", but to extract the timeseries of each parcel, right? So the function name doesn't fit to the aim of this function.

- https://github.com/jadecci/cbpp/blob/dd27c86fedcd08d6e0849acdbf661e61e4d4783d/generalisability_CBPP/generalise_data_proc.m#L132

  Maybe put a comment on how was the confound file generated? Same for the other datasets.

- https://github.com/jadecci/cbpp/blob/dd27c86fedcd08d6e0849acdbf661e61e4d4783d/generalisability_CBPP/generalise_data_proc.m#L11 (and the next line)

  Shouldn't these two files in csv format instead of .mat, as you described in the README?

**Comment by jadecci** [comment]
- Regarding the eNKI phenotype files, yes as long as no more update from the eNKI side. If the server-side file is updated, then the file content might all be changed.
- For the `benchmarks` README, yes. I have added the information to the table titles and headers.
- For the `HCP_CBPP` README, I added in the description that this is using 300-parcel resolution.
